- name: Manage Docker Private Registry
  hosts: localhost
  gather_facts: no
  vars:
    registry_url: "http://<registry-url>"
    repositories: []  # Will be populated dynamically
    deleted_repositories: []

  tasks:
    - name: Get the list of all repositories
      uri:
        url: "{{ registry_url }}/v2/_catalog"
        method: GET
        return_content: yes
      register: repositories_response

    - name: Extract repository names
      set_fact:
        repositories: "{{ repositories_response.json.repositories }}"

    - name: Debug repository list
      debug:
        var: repositories

    - name: Iterate over all repositories and delete their tags
      block:
        - name: Get tags for each repository
          uri:
            url: "{{ registry_url }}/v2/{{ item }}/tags/list"
            method: GET
            return_content: yes
          loop: "{{ repositories }}"
          loop_control:
            loop_var: repository
          register: tags_response

        - name: Iterate over tags in each repository
          block:
            - name: Get manifest digest for each tag
              uri:
                url: "{{ registry_url }}/v2/{{ repository }}/manifests/{{ tag }}"
                method: GET
                headers:
                  Accept: "application/vnd.docker.distribution.manifest.v2+json"
                status_code: [200, 404]
              loop: "{{ tags_response.results[loop.index0].json.tags }}"
              loop_control:
                loop_var: tag
              register: manifest_response

            - name: Delete manifest by digest
              uri:
                url: "{{ registry_url }}/v2/{{ repository }}/manifests/{{ manifest_response.results[loop.index0].headers['Docker-Content-Digest'] }}"
                method: DELETE
                status_code: [202, 404]
              loop: "{{ manifest_response.results }}"
              when: manifest_response.results[loop.index0].headers['Docker-Content-Digest'] is defined
      when: repositories | length > 0

    - name: Run garbage collection
      command: >
        docker exec <registry-container> registry garbage-collect /etc/docker/registry/config.yml
      become: true
      when: repositories | length > 0
